#!/bin/sh
# INSTALL THE BINDING AS A PACKAGE, and then consume it as one.
#
# CRITICS round 12 #6: "um exemplo consumidor em diretorio temporario deve depender apenas de um
# artefato instalado/empacotado". The consumer smoke gets half of that — the application is built
# outside the checkout — but it still points `-I` and `-L` at a build directory, which is not a
# dependency, it is a path that happens to exist. This closes the other half: lay the artifacts out
# as a dub package and let dub resolve it.
#
# There is nothing clever here, and that is the finding: the whole package is an import path, two
# archives and eleven lines of dub.json. What was missing was never machinery — it was that nobody
# had tried, which is also how three papercuts survived until somebody wrote an application.
#
#   install.sh <gen dir> <build dir> <prefix> <pkg name> <qt libs...>
set -eu
GEN="$1"; BDIR="$2"; PREFIX="$3"; PKG="$4"; shift 4
LIBS="$*"

rm -rf "$PREFIX"; mkdir -p "$PREFIX/lib"
cp -r "$GEN" "$PREFIX/source"
# Both compilers' archives, selected by dub's `lflags-<compiler>` — one package, either compiler.
for a in "$BDIR"/libbinding_*.a "$BDIR/libshims.a"; do [ -f "$a" ] && cp "$a" "$PREFIX/lib/"; done

# `libs` as PLAIN NAMES, not the pkg-config line: dub passes them to the compiler's -L machinery,
# and a `-lQt6Widgets` here would arrive as `--l-lQt6Widgets`.
qlibs=""
for l in $LIBS; do
  case "$l" in -l*) n=${l#-l} ;; *) continue ;; esac
  qlibs="$qlibs\"$n\", "
done

cat > "$PREFIX/dub.json" <<EOF
{
  "name": "$PKG",
  "description": "Qt binding for D, generated by qt-dlang-gen. Not hand-written; regenerate rather than patch.",
  "targetType": "sourceLibrary",
  "importPaths": ["source"],
  "lflags-ldc": ["-L\$PACKAGE_DIR/lib", "--start-group", "-lbinding_ldc2", "-lshims", "--end-group"],
  "lflags-dmd": ["-L\$PACKAGE_DIR/lib", "--start-group", "-lbinding_dmd", "-lshims", "--end-group"],
  "libs": [${qlibs}"stdc++"]
}
EOF
echo "install OK: $PKG -> $PREFIX ($(du -sh "$PREFIX" | cut -f1))"
