#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Marcelo A Caetano
# SPDX-License-Identifier: BSL-1.0
#
# LAY THE GENERATED BINDINGS OUT AS ONE PUBLISHABLE dub PACKAGE.
#
#   tools/ci/assemble-bindings.sh <out dir> [<spec>:<subpackage> ...]
#
# `tests/install.sh` already turns ONE generated binding into a self-describing dub package. This
# runs it once per binding into a subdirectory and writes the root `dub.json` that names them as
# subpackages, which is the shape a consumer asks for as `dside:quick`.
#
# THE PACKAGE VERSION IS THE Qt VERSION, and that is the point of the layout rather than a
# convenience. The repository is tagged `v6.12.0` for the bindings generated against Qt 6.12.0, so
# `"dside:quick": "~>6.12.0"` resolves to exactly the releases whose ABI matches — dub's `~>` is
# >=6.12.0 <6.13.0, and a Qt minor is precisely the boundary across which these are not
# interchangeable. The constraint a user would have written anyway is the one the versioning gives
# them for free.
#
# IT DERIVES THE LINK LINE, it does not carry one. Each build directory holds `qtlibs.txt`, which
# the build writes for exactly this reason (see qtd_build.d) — a second copy of a module list is how
# `Qt6QuickLayouts` came to be missing from one of two spellings and left eighteen documents
# unplaced. Nothing here names a Qt module.
set -euo pipefail

OUT=${1:-}
[ -n "$OUT" ] || { sed -n '5,7p' "$0"; exit 2; }
shift || true

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

# WHAT GETS PUBLISHED, and this list is a policy rather than a discovery. Every generated tree under
# `generated/` is a binding, but most are fixtures — wraptest is three classes, corpustypes exists
# for the qmltc corpus, and the non-wrapper qtwidgets is the legacy path. Publishing those would ask
# a user to choose between names that do not mean what they look like. Add a line to add a package.
# WebEngine is deliberately absent. `spec_cxx_webengine_wrap.json` exists but nothing in
# reggaefile.d builds it — what the build produces is `cxx-webengine`, which is the LEGACY
# (non-wrapper) path, and shipping one non-wrapper package beside three wrapper ones would hand a
# user two different lifetime models under one package name. Wire the wrap spec into the build
# first, then add it here.
DEFAULT_SET="cxx-quick:quick cxx-qtwidgets-wrap:widgets cxx-controls:controls"
SET=${*:-$DEFAULT_SET}

QTVER=$(pkg-config --modversion Qt6Core 2>/dev/null || echo unknown)
QTMINOR=${QTVER%.*}

rm -rf "$OUT"; mkdir -p "$OUT"
subs=""
made=0
skipped=""

for entry in $SET; do
    spec=${entry%%:*}
    pkg=${entry##*:}
    gen="$ROOT/generated/qt-$QTMINOR/$spec"
    bdir="$ROOT/.build/qt-$QTMINOR-$spec"

    # A BINDING THAT WAS NOT BUILT IS NAMED, NOT PASSED OVER. Assembling a package that silently
    # contains three of the four things it claims is the failure this whole pipeline exists to
    # avoid: the tag goes out, the consumer asks for `dside:controls`, and dub answers that no such
    # subpackage exists — long after the run that should have said so was green.
    if [ ! -d "$gen" ] || [ ! -f "$bdir/qtlibs.txt" ]; then
        skipped="$skipped $spec"
        continue
    fi

    libs=$(cat "$bdir/qtlibs.txt")
    # install.sh speaks the compiler's `-L-l` escape; qtlibs.txt holds the plain `-l` form.
    esc=$(printf '%s' "$libs" | sed 's/-l/-L-l/g')
    sh "$ROOT/tests/install.sh" "$gen" "$bdir" "$OUT/$pkg" "$pkg" $esc -L-lstdc++ >/dev/null
    subs="$subs\"./$pkg\", "
    made=$((made + 1))
    echo "  $pkg <- $spec ($(du -sh "$OUT/$pkg" | cut -f1))"
done

[ -n "$skipped" ] && {
    echo "assemble-bindings: NOT BUILT, so not packaged:$skipped" >&2
    echo "    Run the build for those bindings first, or name an explicit set." >&2
    exit 1
}
[ "$made" -gt 0 ] || { echo "assemble-bindings: nothing to assemble" >&2; exit 1; }

cat > "$OUT/dub.json" <<EOF
{
  "name": "dside",
  "license": "BSL-1.0",
  "description": "Qt bindings for D, generated by xiboca (extern(C++), no hand-written C shim). The package version is the Qt release these were generated against.",
  "copyright": "Copyright (c) 2026 Marcelo A Caetano",
  "targetType": "none",
  "subPackages": [${subs%, }]
}
EOF
cp "$ROOT/LICENSE" "$OUT/LICENSE"
mkdir -p "$OUT/LICENSES"
cp "$ROOT/LICENSES/BSL-1.0.txt" "$OUT/LICENSES/BSL-1.0.txt"

# WHICH Qt THESE ARE FOR, at the root as well as in every subpackage. A consumer who has unpacked
# the tag and is wondering why a symbol is missing should not have to open a subdirectory to learn
# that this is the 6.11 binding and their Qt is 6.12.
cat > "$OUT/qt-version.txt" <<EOF
$QTVER
EOF
cp "$ROOT/qt-version.txt.license" "$OUT/qt-version.txt.license" 2>/dev/null || true

echo "assemble-bindings OK: $made subpackage(s) for Qt $QTVER in $OUT ($(du -sh "$OUT" | cut -f1))"
