#!/bin/sh
# THIN STUBS FOR THE QML RUNTIME UNIT, GENERATED FROM IT (critics r13 #3).
#
# The product boundary the audit asks for is not "the source lives in another file" — it is that a
# binding with no QtQml does not carry the QML runtime at all. Measured before this existed: the
# QtWidgets and libsample archives each contained qtdmoc_qml.o.
#
# Two ways were on the table, and the audit named both: version the D side, or thin stubs. Versioning
# meant guarding seventeen declaration/wrapper pairs in the shared qtmoc.d, one of which
# (`qtd_parser_status`) is reached from `classBegin` — a path with no QML in sight. Stubs keep the
# ABI identical and touch no D at all.
#
# The usual objection to stubs is drift: two lists that must agree, and one of them edited. So the
# stub is not written by hand — it is GENERATED from the unit's own signatures on every build. A new
# export appears in both or in neither.
#
# Return values: a pointer type gets nullptr, everything else 0. That is exactly what the guarded
# bodies in qtdmoc_qml.cpp already return when QTD_HAVE_QML is undefined, so a non-QML binding
# behaves the same as it did when it compiled the whole unit to no-ops.
set -eu
[ $# -eq 2 ] || { echo "usage: qmlstub.sh <qtdmoc_qml.cpp> <out.cpp>" >&2; exit 2; }
src=$1; out=$2

{
  echo "// GENERATED by tools/qmlstub.sh from $(basename "$src") — do not edit."
  echo "// No-op definitions of the QML runtime's exports, for a binding with no QtQml. See the"
  echo "// script for why these are generated rather than written."
  echo
  # `extern "C" <ret> qtd_name(args) {` -> a body that returns a zero of <ret>. A signature may
  # span two lines (five of the seventeen do), so continuations are joined before matching — the
  # first version of this script silently produced twelve stubs out of seventeen, and a stub list
  # that is quietly short is the drift it exists to prevent.
  # A DECLARATION (`…);`) is not a definition and must not be stubbed: the QML unit forward-declares
  # `qtd_prop_get_obj`, which the shared unit defines, and gluing it to the next signature produced
  # one line with two functions on it — and a duplicate symbol at link time.
  awk '/^extern "C" /{
         acc=$0
         while (acc !~ /\{/ && acc !~ /;[[:space:]]*$/ && (getline nxt) > 0) {
             sub(/^[[:space:]]+/, " ", nxt); acc = acc nxt
         }
         # A one-line definition (`… { … }`) is a definition too: keep the signature, drop the body.
         if (acc ~ /\{/) { sub(/\{.*$/, "{", acc); print acc }
       }' "$src" \
    | sed 's/^extern "C" //; s/ *{[[:space:]]*$//' | while IFS= read -r sig; do
      case "$sig" in
        *"*"*")"*|*"* "*")"*) ret=ptr ;;
        "void "*) ret=void ;;
        *) ret=zero ;;
      esac
      # a pointer RETURN is the leading token before the name, not a pointer argument
      lead=${sig%%(*}
      case "$lead" in
        void\ *)         body="" ;;
        *\**)            body=" return nullptr;" ;;
        *)               body=" return 0;" ;;
      esac
      # unnamed parameters: the stub uses none of them
      printf 'extern "C" %s {%s }\n' "$sig" "$body"
  done
} > "$out"

n=$(grep -c '^extern "C"' "$out" || true)
[ "$n" -gt 0 ] || { echo "qmlstub: produced no stubs from $src — the signature shape changed" >&2; exit 1; }
echo "qmlstub: $n no-op export(s) -> $(basename "$out")"
